### ISSUE TITLE
Mismatch requirements between gitpython and gitdb

### ISSUE THREAD

**Issue by fmigneault** [gitpython-developers/GitPython#984] opened 2020-02-17 19:10 UTC
Since: 
https://github.com/gitpython-developers/gitdb/commit/db9a65e3b0eceb9c52359273afb3313860e5e322#diff-cb33ff3d8cc897a097528366a431b077

`gitdb.utils.compat` doesn't exist
This makes any version prior to https://github.com/gitpython-developers/GitPython/tree/3.0.6
to fail because the requirement is not limited to `<3.0.2` in the requirements :
https://github.com/gitpython-developers/GitPython/blob/3.0.6/requirements.txt

**Comment by Harmon758** [comment] 2020-02-17 19:11
Duplicate of #983

**Closed by Harmon758** 2020-02-17 19:11 UTC
