### ISSUE TITLE
readthedocs.io API Reference only shows headings as of 3.1.15

### ISSUE THREAD

**Issue by connordelacruz** [gitpython-developers/GitPython#1235] opened 2021-05-12 19:41 UTC
Currently, the API reference section for GitPython on readthedocs.io just shows the headings:
![sc 2021-05-12 at 2 34 29 PM](https://user-images.githubusercontent.com/10520994/118034082-2de8d300-b32f-11eb-9909-2843340c186c.png)

This is happening for version 3.1.15, "stable", and "latest":
- https://gitpython.readthedocs.io/en/3.1.15/reference.html
- https://gitpython.readthedocs.io/en/stable/reference.html
- https://gitpython.readthedocs.io/en/latest/reference.html

3.1.14 looks fine, however:
![sc 2021-05-12 at 2 37 10 PM](https://user-images.githubusercontent.com/10520994/118034413-920b9700-b32f-11eb-8cc7-c16c12940a45.png)
https://gitpython.readthedocs.io/en/3.1.14/reference.html

it seems like something about the autodocs changed between 3.1.14 and 3.1.15

**Comment by Yobmod** [comment] 2021-06-21 05:00
Hi,

I've been looking into this, and I don't think it has anything to do with typing. I've checked every PR and all the commits in the 1 typing PR between v3.1.14 and v3.1.15.

However, I eventually noticed that Gitdb docs are also broken since v4.0.6. That was released 25th March, in between Gitpython v3.1.14 and v3.1.15, so changes there were pulled across.

**Comment by Byron** [comment] 2021-06-22 00:01
> I've been looking into this, and I don't think it has anything to do with typing. I've checked every PR and all the commits in the 1 typing-PR between v3.1.14 and v3.1.15.

Thanks a lot, me concluding that this happened due to typing was an unvalidated assumption, my apologies.

> When the docs are built, where do the files go?

From the `doc` directory `make html` should build docs into the `doc/html` subdirectory if `sphinx-build` is available in the PATH.

> Another thing i noticed: pythonpackage.yml used to import gibdb and ssmap as submodules. This now fails to pass tests unless gitdb is also pip installed (fails with "fatal: exec 'rev-list': cd to 'gitdb/ext/smmap' failed: No such file or directory" and "ModuleNotFoundError (No module named 'gitdb')".

That's interesting, [CI seems to be green](https://github.com/gitpython-developers/GitPython/runs/2876201419?check_suite_focus=true). However, that in conjunction with some changes to GitDb might actually help to solve this, and locally reproducing the docs build is certainly the way to go.

**Comment by Yobmod** [comment] 2021-06-23 01:42
Yep, the CI works because gitdb was added to test-requirements.txt in May (in order to get CI to pass). 
So in pythonpackage.yml gitdb is getting imported from test-requirements.txt after importing it as a submodule and masking any potential problems from gitdb.

**Comment by Byron** [comment] 2021-06-23 12:14
<img width="1181" alt="Screenshot 2021-06-23 at 20 11 45" src="https://user-images.githubusercontent.com/63622/123094580-9d3e0080-d45f-11eb-9b0e-9a4194ecf649.png">

I think it's fixed now. Please see the linked issue for details.

**Closed by Byron** 2021-06-23 12:14 UTC
Labels: acknowledged, help wanted
