### ISSUE TITLE
Can't catch GitCommandError

### ISSUE THREAD

**Issue by zerothi** [gitpython-developers/GitPython#1924] opened 2024-05-31 20:07 UTC
I am trying to do a cherry-pick, but abort when it fails:

```python
import git
...
git = repo.git
try:
    git.cherry_pick(commit)
except git.GitCommandError as e:
    git.cherry_pick(abort=True)
...
```
but I get this:
```
    except git.GitCommandError as e:
   TypeError: catching classes that do not inherit from BaseException is not allowed
```
Now I can obviously do `except Exception as e`... But, I would like to be explicit to defer code-paths.

**Comment by Byron** [comment] 2024-06-01 06:17
Thanks for reporting!

This seems fixable and testable, and even though I don't know what's the best way to fix this, somebody coming along will.
Thanks for helping.

**Comment by EliahKagan** [comment] 2024-06-01 14:02
The problem is not with the `GitCommandError` exception, which [works fine in `except` clauses](https://github.com/search?q=repo%3Agitpython-developers%2FGitPython%20%22except%20GitCommandError%22&type=code) and, like all exceptions in Python code, does derive ultimately from `BaseException`.

This is instead a bug in the code you showed. That code does not catch that exception, because that exception is not what really appears in the `except` clause. The problem is this assignment statement:

```python
git = repo.git
```

Before that, `git` was the `git` module, whose `GitCommandError` attribute is an exception. After that, `git` is an instance of the `Git` class. All subsequent uses of `git` are as if `repo.git` had been used. So then you have:

```python
except git.GitCommandError as e:
```

Because you reassigned `git`, this is like:

```python
except repo.git.GitCommandError as e:
```

In most cases, a bug like this would result in an `AttributeError`. But the attributes of a `Git` instance, unless otherwise present, are dynamically generated functions that, when called, invoke the `git` executable to run `git` commands. For example, `repo.git.gc` is a function that, when called, runs a `git gc` command. Likewise, `repo.git.GitCommandError` is a function that, when called, runs a `git GitCommandError` command.

(Of course, the `git` executable has no `GitCommandError` subcommand. So calling it would fail, unless a `GitCommandError` alias has been defined, a `git-GitCommandError` script can be found in `$PATH`, or a future or alternative version of `git` is in use that has such a subcommand. Being open-ended in this way allows `Git` instances to be usable for all those things. That the `git` executable recognizes no `GitCommandError` subcommand is not relevant to what you are observing, though, since you you are attempting to catch `repo.git.GitCommandError`, not to call it. The key is that attempting to catch this function as though it were an exception definitely fails: not only is it not an exception, it is not even a type.)

**Closed** 2024-06-02 06:31 UTC
Labels: acknowledged, help wanted

**Comment by zerothi** [comment] 2024-06-03 11:30
Ha, so true!!! How did I miss that :) Thanks!

**Comment by zerothi** [comment] 2024-06-03 11:41
Might I propose that https://gitpython.readthedocs.io/en/latest/tutorial.html#using-git-directly changes `git = repo.git` to something else? That was my inspiration ;)

**Comment by Byron** [comment] 2024-06-04 04:49
Thanks so much for sharing, I wasn't aware!

Do you think you could give that change a try? It's in `test/test_doc.py`, and it's CI-tested so nothing can go wrong.
I would love it if that could be contributed.
