### ISSUE TITLE
Diff broken in 1.0.2

### ISSUE THREAD

**Issue by Shrews** [gitpython-developers/GitPython#382] opened 2016-02-12 14:37 UTC
I believe this change breaks diff functionality in 1.0.2:

https://github.com/gitpython-developers/GitPython/commit/332521ac1d94f743b06273e6a8daf91ce93aed7d

Using OS X and git 2.5.4, the generated command puts a space between the diff -U option and its value. This causes an exception as git insists on there being no space between them.

**Comment by Byron** [comment] 2016-02-13 17:14
Thanks for getting down to the root of the problem. This change was introduced to solve a particular (and to me unknown) problem, and I am wondering how to solve this issue without introducing breakage for someone else.

When looking [at the code](https://github.com/gitpython-developers/GitPython/blob/55db0fcce5ec5a92d2bdba8702bdfee9a8bca93d/git/diff.py#L73-L113), I couldn't find any usage of the `-U` option described here.

Can you help me to reproduce the problem ?

**Comment by Shrews** [comment] 2016-02-15 13:43
I believe the U option is being passed as part of the kwargs. Actually experiencing this with a tool called gertty. Here is the line with the diff() call where the crash occurs:

https://github.com/openstack/gertty/blob/master/gertty/gitrepo.py#L390-L391

Also, see new comments in: https://github.com/gitpython-developers/GitPython/commit/332521ac1d94f743b06273e6a8daf91ce93aed7d

**Comment by Byron** [comment] 2016-02-21 13:05
What about using the respective long option instead, i.e. `--unified` ? The line in question would then look like this:
```python
extra_contexts, oldc.diff(
     newc, color='never',create_patch=True, unified=context))
```

**Comment by Shrews** [comment] 2016-02-21 13:30
Yes, the long option works. Buts that's nothing more than a workaround.

**Comment by Byron** [comment] 2016-02-21 13:37
Great to hear it works ! Where else are you having problems with that particular behaviour of the git executable when used with gitpython ?
To me it seems the issue is fixed, even without having to change defaults that are likely to break other code elsewhere.

**Comment by jeblair** [comment] 2016-02-21 15:49
It might be helpful to know what commit 332521a was attempting to fix.  It seems like we have traded something unknown to us being broken for the breakage described in this issue.  A quick check of some random diff options suggests that this behavior change will affect not only "-U" in git diff, but also "-C", "-M', and "-B".  These are likely to cause GitPython users to run into difficult-to-diagnose problems when they attempt to use these options in their customary form.

With an understanding of what 332521a was fixing, we could evaluate a way forward -- perhaps there is another way to accomplish what was intended there, or perhaps we need to support different behaviors for different git subcommands, or perhaps we need to say that single-char options with arguments are not supported and return a useful error to gitpython users.

**Comment by Shrews** [comment] 2016-02-25 13:42
Agree with jeblair here. I find it odd to consider it "fixed" by putting the responsibility on users of the library to modify their once-working code.

**Comment by Byron** [comment] 2016-02-27 09:02
Thanks for your feedback ! 
When looking at #341, it appears that fixing it for one is breaking it for another. Even though a viable solution could be to enforce long options for diff-related commands, I would love to be able to configure this particular flag `split_single_char_options` on a per-command basis.
That way, the diff implementation could 'fix it by default' and thus prevent the unexpected behaviour experienced here.

Just to unclutter this issue a bit, I would like to move attention to the linked issue, and close this one. In the meanwhile, one could go with the proposed workaround of using long options instead of short ones.

**Closed by Byron** 2016-02-27 09:02 UTC
