### ISSUE TITLE
GitPython3 breaks install via setup.py

### ISSUE THREAD

**Issue by jeremyjjbrown** [gitpython-developers/GitPython#957] opened 2019-10-31 15:45 UTC
I get 

```
Collecting GitPython>=2.1.11 (from gitops==0.0.1)
  Downloading https://files.pythonhosted.org/packages/be/0f/b180ddaf91429d6ebd7d46d022c31522e05ce7631b41da3901d9e4338c64/GitPython-3.0.4.tar.gz (432kB)
    Complete output from command python setup.py egg_info:
    /usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    error in GitPython setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-6WGL_f/GitPython/
You are using pip version 8.1.2, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
Pip is updated as is setup tools, in docker centos:centos7. Here is the setup.py
```
from setuptools import setup

setup(
    name='gitops',
    version='0.0.1',
    packages=[
        'gitops',
    ],
    license='Properitary unless otherwise stated',
    long_description=open('README.md').read(),
    install_requires=[
        'GitPython>=2.1.11',
        'boto3>=1.9.119',
        'click>=7.0',
        'future>=0.17.1',
        'requests>=2.22.0'
    ],
    scripts=[
        'bin/apply_ecfs_changes',
        'bin/cfctl',
        'bin/delete_ecfs_changes',
        'bin/git-changes',
        'bin/sleep-ecfs',
        'bin/sleep-filter'
    ]
)
```

Pinning `'GitPython==2.1.11',` abates the issue.

**Comment by Byron** [comment] 2019-11-05 00:31
Thanks for the post! Even though I didn't try to reproduce the issue, I believe it would be possible with the information you provided.

However, I have the feeling it's an issue with pip rather than GitPython. The reason is that it appears to try to download version `3.x` if the client specifies `>=2.x`, which clearly breaks [semver](https://semver.org) as it increments the major version. GitPython 3.0 will not support python 2.7, and uses different syntax for requirements (i.e. `gitdb2 (>=2.0.0)`), which is incompatible with that version of `pip` and/or python 2.7.

This means the mere existence of a more recent but incompatible version of GitPython will break as pip ignores semantic versioning. As a workaround, specifying the exact version in the client requirements seems to be a viable.

**Comment by jeremyjjbrown** [comment] 2019-11-13 19:52
@Byron Thanks, that makes a lot of sense and was what I had already done in the meantime to fix my issue.

**Comment by Byron** [comment] 2019-11-14 00:55
Thank you! I am closing the issue as there is nothing that can be done on the side of GitPython.

**Closed** 2019-11-14 00:55 UTC
Labels: acknowledged, rejected
