### ISSUE TITLE
GitPython - [CRITICAL] No suitable gitfs provider module is installed - even installation gone through

### ISSUE THREAD

**Issue by ronak2303** [gitpython-developers/GitPython#1045] opened 2020-07-31 16:38 UTC
i am trying to install gitpython 2.0.9 on salt master.
i tried installing gitpython but when i put gitfs in master i got message "[CRITICAL] No suitable gitfs provider module is installed."
so tried installing gitpython mutliple times in between i recycled salt-master twice, 1st when i added gitfs entry and 2nd when i remove gitfs entry.
----------
          ID: GitPython
    Function: pip.installed
        Name: GitPython < 2.0.9
      Result: True
     Comment: All packages were successfully installed
     Started: 15:58:24.339041
    Duration: 1553.285 ms
     Changes:
              ----------
              GitPython==2.0.8:
                  Installed

once i did that and i tried installing gitpython, i started getting below error to install gitpython 2.0.9

          ID: GitPython
    Function: pip.installed
        Name: GitPython < 2.1.14
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1951, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/pip_state.py", line 812, in installed
                  **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/pip_state.py", line 314, in _check_if_installed
                  for version in reversed(available_versions):
              TypeError: argument to reversed() must be a sequence
     Started: 16:06:01.701500
    Duration: 368661.261 ms
     Changes:

**Comment by Byron** [comment] 2020-08-12 12:26
Despite best attempts I am quite lost and fail to understand how that issue could be reproduced, and if this even is anything that GitPython can affect in some way.
After all, it's a python package that seems to install fine using `pip`.

As the problem stated here seems not to be caused by GitPython, I am closing the issue, but invite for further clarifications that help shed some light on what GitPython should or could do to make this work.
Thanks for your understanding.

**Closed by Byron** 2020-08-12 12:26 UTC
