### ISSUE TITLE
is_git_dir() doesn't handle symbolic refs in HEAD (ref: refs/heads/...)

### ISSUE THREAD

**Issue by jahogan** [gitpython-developers/GitPython#111] opened 2013-06-27 11:08 UTC
I have a bare repo where HEAD is a symbolic reference, I.e. it contains "ref: refs/heads/...". GitPython doesn't handle this because is_git_dir() just checks it starts with "refs" which it doesn't, so constructing a Repo object fails.

https://github.com/gitpython-developers/GitPython/blob/0.3/git/repo/fun.py#L30

it also seems to be in master:
https://github.com/gitpython-developers/GitPython/blob/master/git/util.py#L171

see also the code in git itself:
https://github.com/git/git/blob/master/path.c#L238

**Comment by Byron** [comment] 2015-01-12 11:59
The code in question was improved in the most recent version on master, and even though I have evaluated your hints, I am quite unable to reproduce the issue you stated.
Would you mind retrying with the latest version on github, or provide me with more information that allows me to reproduce your particular issue.

I will close this issue, and reopen it once I hear back from you - thanks for your understanding.

**Closed by Byron** 2015-01-12 11:59 UTC
Labels: feedback

**Comment by Byron** [comment] 2015-01-12 12:05
Video about the fix can be found [on youtube](http://youtu.be/HH5PlbjQ81M)

**Comment by jahogan** [comment] 2015-01-12 12:39
Thanks for looking into this. I can't remember exactly what I was trying to do at the time. I think from my log that I was trying to get grokmirror to work. I've given it a quick sanity check with git-python 0.3.2.1 (latest in gentoo), and it seems to work, even with comments in the git config file, so yeh, fixed from my point of view too.

**Comment by Byron** [comment] 2015-01-12 12:40
Great to hear, and thanks for the feedback !
