### ISSUE TITLE
Exception when deleting a reference

### ISSUE THREAD

**Issue by sc68cal** [gitpython-developers/GitPython#299] opened 2015-06-10 13:55 UTC
This is from [stackforge/gertty](https://github.com/stackforge/gertty)

```
2015-06-10 09:50:33,725 Exception running task <PruneChangeTask 2964>
Traceback (most recent call last):
  File "/Users/scollins/src/stackforge/gertty/gertty/sync.py", line 1306, in _run
    task.run(self)
  File "/Users/scollins/src/stackforge/gertty/gertty/sync.py", line 1225, in run
    repo.deleteRef(change_ref)
  File "/Users/scollins/src/stackforge/gertty/gertty/gitrepo.py", line 272, in deleteRef
    git.Reference.delete(repo, ref)
  File "/Library/Python/2.7/site-packages/git/refs/symbolic.py", line 410, in delete
    os.remove(abs_path)
OSError: [Errno 1] Operation not permitted: '/Users/scollins/src/openstack/neutron/.git/refs/changes/83/171983'
```

Here's what the git repo looks like in that hive

```
scollins@Sean-Collins-MBPr15 ~ » find /Users/scollins/src/openstack/neutron/.git/refs/changes/83/                                                                                                       1 ↵
/Users/scollins/src/openstack/neutron/.git/refs/changes/83/
/Users/scollins/src/openstack/neutron/.git/refs/changes/83//171983
/Users/scollins/src/openstack/neutron/.git/refs/changes/83//175383
/Users/scollins/src/openstack/neutron/.git/refs/changes/83//175383/4
/Users/scollins/src/openstack/neutron/.git/refs/changes/83//175383/5
/Users/scollins/src/openstack/neutron/.git/refs/changes/83//184383
/Users/scollins/src/openstack/neutron/.git/refs/changes/83//184383/2
/Users/scollins/src/openstack/neutron/.git/refs/changes/83//188883
/Users/scollins/src/openstack/neutron/.git/refs/changes/83//188883/1
/Users/scollins/src/openstack/neutron/.git/refs/changes/83//188883/2
/Users/scollins/src/openstack/neutron/.git/refs/changes/83//188983
/Users/scollins/src/openstack/neutron/.git/refs/changes/83//188983/1
```

**Comment by Byron** [comment] 2015-06-10 15:09
To me it seems this is not a problem of GitPython directly, as the user running GitPython doesn't seem to have permissions to remove a file from the filesystem.

You should be able to reproduce this kind of error by running `git br -D changes/83/171983` *as the user* that showed the given exception.

Please let me know what you could find out..

**Comment by Byron** [comment] 2015-06-10 20:08
You can watch the development stream [on youtube](https://youtu.be/WCX4AfQW64o).

*`GitPython #8 [issue 296 - handle missing fetch-refspec gracefully]`*

[\![thumb](https://i.ytimg.com/vi/WCX4AfQW64o/mqdefault.jpg)](https://youtu.be/WCX4AfQW64o)

**Comment by Byron** [comment] 2015-06-10 20:09
You can watch the development stream [on youtube](https://youtu.be/MvqyZ1TwcX8).

*`GitPython #9 [issue 299 - errors when deleting a branch]`*

[\![thumb](https://i.ytimg.com/vi/MvqyZ1TwcX8/mqdefault.jpg)](https://youtu.be/MvqyZ1TwcX8)

**Comment by sc68cal** [comment] 2015-06-16 18:02
```
Traceback (most recent call last):
  File "/Users/scollins/src/stackforge/gertty/gertty/sync.py", line 1306, in _run
    task.run(self)
  File "/Users/scollins/src/stackforge/gertty/gertty/sync.py", line 1225, in run
    repo.deleteRef(change_ref)
  File "/Users/scollins/src/stackforge/gertty/gertty/gitrepo.py", line 272, in deleteRef
    git.Reference.delete(repo, ref)
  File "/Library/Python/2.7/site-packages/git/refs/symbolic.py", line 410, in delete
    os.remove(abs_path)
OSError: [Errno 1] Operation not permitted: '/Users/scollins/src/stackforge/fuel-astute/.git/refs/changes/30/174830'
scollins@SeanColnsMBPr15 ~/src/stackforge/fuel-astute ±master » git branch -D changes/30/174830  1 ↵
error: branch 'changes/30/174830' not found.
```

**Comment by Byron** [comment] 2015-06-18 07:32
Posting a stack-trace of the attempted deletion of a non-existent branch without any additional statement on how git-python would be involved puzzles me. After all, the question was if the user running the git-python script is actually allowed to delete a branch in terms of the required filesystem permissions.

From what I see, this isn't an issue of git-python, which is why it seems alright to close it.

**Closed by Byron** 2015-06-18 07:32 UTC
Labels: waiting for feedback

**Comment by sc68cal** [comment] 2015-06-18 17:40
>Posting a stack-trace of the attempted deletion of a non-existent branch without any additional statement on how git-python would be involved puzzles me

This is coming a stack trace from Gertty, as stated in the first post, which uses git-python!

> After all, the question was if the user running the git-python script is actually allowed to delete a branch in terms of the required filesystem permissions.

Yes - the same user running Gertty is the same user that owns that directory and all files under it.

Please, I would appreciate reopening this issue so we can continue to diagnose.

**Comment by Byron** [comment] 2015-06-19 06:59
Unfortunately I don't believe this is an issue of git-python, as it looks like `gertty` wants to delete a non-existing branch but has no permission to do so. My guess is that `gertty` is running as a user who has no permission to alter the repository, for some reason.
I have repeated myself many times already, which usually shows there is a dead-end here.

**Comment by sc68cal** [comment] 2015-06-30 14:06
> My guess is that gertty is running as a user who has no permission to alter the repository, for some reason.

I believe this is incorrect - `gertty` is running as my user account and is manipulating a git tree that I own.
