### ISSUE TITLE
fetch all refs prepends 'refs/remotes' and crashes.

### ISSUE THREAD

**Issue by thorsummoner** [gitpython-developers/GitPython#497] opened 2016-08-13 05:46 UTC
More specifically, fetching the refspec `+refs/*:refs/*` can somehow become 'refs/remotes/<orignal_ref>' and  thus crashes with "ValueError: refs/remotes/<original_ref>  does not exist", as that ref name it made up does not exist :)

Here's the objects and their values for 5depths:
https://gist.github.com/thorsummoner/84c7a9aa989614227db7abb1c8bbc7ab

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/pdb.py", line 1314, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib/python2.7/pdb.py", line 1233, in _runscript
    self.run(statement)
  File "/usr/lib/python2.7/bdb.py", line 400, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "gh_mirror.py", line 2, in <module>
    """
  File "gh_mirror.py", line 172, in main
    fetch_info.ref.commit.hexsha,
  File "/home/git/.local/lib/python2.7/site-packages/git/refs/symbolic.py", line 183, in _get_commit
    obj = self._get_object()
  File "/home/git/.local/lib/python2.7/site-packages/git/refs/symbolic.py", line 176, in _get_object
    return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
  File "/home/git/.local/lib/python2.7/site-packages/git/refs/symbolic.py", line 125, in dereference_recursive
    hexsha, ref_path = cls._get_ref_info(repo, ref_path)
  File "/home/git/.local/lib/python2.7/site-packages/git/refs/symbolic.py", line 157, in _get_ref_info
    raise ValueError("Reference at %r does not exist" % ref_path)
ValueError: Reference at u'refs/remotes/master' does not exist
```

Let me know if more data is needed to debug.

All I'm doing to get this error

``` python
import git as gitpython

gitpython_repo = gitpython.Repo('repo/path/here')

updates = gitpython_repo.remote().fetch(
    refspec=['+refs/*:refs/*',],
    force=True,
)

for fetch_info in updates:
    print(fetch_info.ref.commit.hexsha)
```

**Comment by Byron** [comment] 2016-08-14 08:18
Thanks for the report ! Can you clarify and tell me which version of `gitpython` and `git` you are using ?
Besides, I was running the code to reproduce on the current working dir, which happened to be gitpython repository on master(58934b8):

```bash
➜  GitPython git:(master) ✗ python reproduce.py
Traceback (most recent call last):
  File "reproduce.py", line 7, in <module>
    force=True,
  File "/Users/byron/dev/py/GitPython/git/remote.py", line 743, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress)
  File "/Users/byron/dev/py/GitPython/git/remote.py", line 640, in _get_fetch_info_from_stderr
    finalize_process(proc, stderr=stderr_text)
  File "/Users/byron/dev/py/GitPython/git/util.py", line 155, in finalize_process
    proc.wait(**kwargs)
  File "/Users/byron/dev/py/GitPython/git/cmd.py", line 335, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: 'git fetch --force -v origin +refs/*:refs/*' returned with exit code 128
stderr: 'fatal: Refusing to fetch into current branch refs/heads/master of non-bare repository'
```

Even though something is wrong, it seems to be something else that git itself is complaining about.
Can you provide more information to reproduce this bug, maybe the repository you are trying to fetch from would help.

<details>
For completeness, here is the content of `reproduce.py`:
```python
import git as gitpython

gitpython_repo = gitpython.Repo('.')

updates = gitpython_repo.remote().fetch(
    refspec=['+refs/*:refs/*',],
    force=True,
)

for fetch_info in updates:
    print(fetch_info.ref.commit.hexsha)
```

**Comment by Byron** [comment] 2017-03-08 05:19
I am closing this issue as it had no interaction for more than 3 months. Please feel free to comment in case you need it to be reopened.

**Closed by Byron** 2017-03-08 05:19 UTC
Labels: waiting for feedback
