### ISSUE TITLE
error running filter branch command using git.filter_branch()

### ISSUE THREAD

**Issue by tamjd1** [gitpython-developers/GitPython#406] opened 2016-04-07 18:02 UTC
I'm trying to run a filter branch command to delete a file and edit commit message related to the file.

The git command on the shell (which works) looks like this:

git filter-branch -f --index-filter 'git rm --cached --ignore-unmatch blah.txt' --msg-filter 'sed "s/blah.txt/DELETED/g"'

I need to run this command programatically so I'm using GitPython's direct git command functionality.

What I've tried so far:

`git.filter_branch(force=True, index_filter="'git rm --cached --ignore-unmatch blah.txt'", msg_filter="'sed \"s/blah.txt/DELETED/g\"'")`

This translated into an inaccurate git command where it added `=` between index_filter and the options instead of a space.

Then I tried:

`git.filter_branch('-f', '--index-filter', "\'git rm --cached --ignore-unmatch blah.txt\'", '--msg-filter', "\'sed \"s/blah.txt/DELETED/g\"\'")`

This translated into the correct git command (shown in the error log) but failed with exit code 1.

```
Traceback (most recent call last):
  File "pygit.py", line 193, in <module>
    _delete_from_git('blah.txt', 'blah.txt')
  File "pygit.py", line 134, in _delete_from_git
    print git.filter_branch('-f', '--index-filter', "\'git rm --cached --ignore-unmatch %s\'" % filepath, '--msg-filter', "\'sed \"s/%s/DELETED/g\"\'" % code)
  File "/usr/local/lib/python2.7/site-packages/git/cmd.py", line 450, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/git/cmd.py", line 902, in _call_process
    return self.execute(make_call(), **_kwargs)
  File "/usr/local/lib/python2.7/site-packages/git/cmd.py", line 695, in execute
    raise GitCommandError(command, status, stderr_value)
git.exc.GitCommandError: 'git filter-branch -f --index-filter 'git rm --cached --ignore-unmatch blah.txt' --msg-filter 'sed "s/blah.txt/DELETED/g"'' returned with exit code 1
stderr: '/usr/libexec/git-core/git-filter-branch: line 341: git rm --cached --ignore-unmatch blah.txt: command not found
index filter failed: 'git rm --cached --ignore-unmatch blah.txt''
```

Any idea why it's failing? Is it even possible to run such commands using GitPython?

**Comment by Byron** [comment] 2016-04-10 10:41
The last chosen form, `git.filter_branch('-f', '--index-filter', "\'git rm --cached --ignore-unmatch blah.txt\'", '--msg-filter', "\'sed \"s/blah.txt/DELETED/g\"\'"` should be the one that allows anything to be executed.

From what I see, it looks like `index filter` tried to execute `git rm --cached --ignore-unmatch blah.txt` as a program. My recommendation is to try using python raw strings to make the arguments more readable, and consider removing all the surrounding `"` characters. They might be the cause of the problem.

As this does not seem to be an issue with GitPython itself, I am closing it proactively. However, please feel free to keep commenting here in case you find out something new in that matter.

**Closed by Byron** 2016-04-10 10:41 UTC
