### ISSUE TITLE
Issues with AutoInterrupt in conjunction with sys.exit on python 3.5

### ISSUE THREAD

**Issue by Heiko-san** [gitpython-developers/GitPython#463] opened 2016-06-06 07:58 UTC
The destructor of the cmd class (actually AutoInterrupt) seems to throw some errors using python 3.5 on Arclinux:

```
Exception ignored in: <bound method Git.AutoInterrupt.__del__ of <git.cmd.Git.AutoInterrupt object at 0x7f7c2b101d68>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/git/cmd.py", line 294, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method Git.AutoInterrupt.__del__ of <git.cmd.Git.AutoInterrupt object at 0x7f7c2b101cc0>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/git/cmd.py", line 294, in __del__
TypeError: 'NoneType' object is not callable
```

It seems this error is triggered by a call to sys.exit(0) at the end of my script, since it doesn't appear if I comment it out.
However I couldn't reproduce this behavior with python 2.7, here sys.exit(0) seems to be working with the module correctly.

What I do is simply clone a repo, add some files commit and push them to a remote.

```
...
repo = Repo.clone_from(target_git_path, target_temp_dir)
...
repo.index.add([file])
...
repo.index.commit('Initial commit')
...
refspec='refs/heads/{0}:refs/heads/{0}'.format(repo.active_branch) # this will fix error if user has set "push.default = matching"
repo.remotes.origin.push(refspec=refspec)
```

**Comment by barry-scott** [comment] 2016-06-06 13:37
I recall from reading another isssue that the problem is that the process object is not being deleted
quickly under python3. This is because of the change in garbage collection between py2 and py3.

Looking at the code it looks like the fix is to explicitly del the process object once it is no longer needed.

This bug I suspect may happen on py2 depending on garbage collector config.

for example from cmd.py:965:

    def __get_object_header(self, cmd, ref):
        cmd.stdin.write(self._prepare_ref(ref))
        cmd.stdin.flush()
        return self._parse_object_header(cmd.stdout.readline())

should be something along these lines:

    def __get_object_header(self, cmd, ref):
        cmd.stdin.write(self._prepare_ref(ref))
        cmd.stdin.flush()
        result = self._parse_object_header(cmd.stdout.readline())
        del cmd
        return cmd

**Comment by Byron** [comment] 2016-06-14 05:25
Which version of GitPython are you using ? It doesn't appear to be the latest one.
The [line in question](https://github.com/gitpython-developers/GitPython/blob/d5739cd466f77a60425bd2860895799f7c9359d9/git/cmd.py#L291) has recently be fixed to check for all the eventualities.
Thanks for the clarification.

**Comment by Byron** [comment] 2016-07-23 13:59
Closed due to inactivity. Please comment to get the issue reopened.

**Comment by barry-scott** [comment] 2016-07-25 08:38
Byron,

Unless you fixed the code this bug is still present in the code base.

Barry

**Comment by Byron** [comment] 2016-07-30 14:34
@barry-scott Can you please answer the question in my last comment, or maybe even provide a test that triggers the issue to allow it to be fixed ? Otherwise this one would be open forever, and I try to avoid that. Thank you.

**Comment by Byron** [comment] 2016-07-30 14:35
And I just noticed that you have not been the OP, yet it seemed you have information about the issue that might help resolving it.

**Comment by barry-scott** [comment] 2016-08-01 10:02
What I recall is that I noticed is the with python2 as soon as the object owning a process resource goes out of scope its is deleted. But in python3 the delete is delayed because of changes in garbage collection.
To force the clean up all objects that control a process resource must be delete explicitly using del proc

For example line 635 in cmd..py returns an instance of AutoInterrupt. All caller will have to be changed to del the returned object after use.

Unless this code change has been made this bug remains unfixed.

**Comment by Byron** [comment] 2016-08-02 03:35
Thanks @barry-scott, I understand. It seems a context manager for the `Cmd` object would be an excellent addition to its API.

**Comment by barry-scott** [comment] 2016-08-02 16:33
I'm pondering if the cmd code should be ripped out and replaced en-mass.
Given the set of requirements that the cmd code has the current implementation is looking far to complex and hard to modify.

We now know that it needs to:
* run a git command 
* allow all stdout to be processed in real time
* allow all strerr to be processed in real time
* allow prompts for input to be processed (for credentials)
* use debug logging to verify operation
* support Windows/macOS/Unix

I think that the above features for cmd can be implemented in a smaller and more obvious way
given all that has been learned with the current implementation.

(I wish you would setup a mailing list for GItPython to allow discussions)

**Comment by Byron** [comment] 2016-08-03 03:26
@barry-scott I believe you are right - the code has been growing just to accommodate all the needs as they arose. This will eventually erode clarity unless some major refactoring or even a rewrite is done.

A good starting point would be to clearly separate the orthogonal parts. Something that comes to mind immediately is the part that streams objects through the git process (a hash goes in, an object comes out, the process is held alive permanently). Another obvious step could be to remove all reliance on the destructors and use context-managers or something like an idempotent `release()` method instead.

On the bright side, one can stake small steps in this endeavour, knowing that the massive reliance on the implementation will show any issues right away when running the tests, some of which might have to be adjusted at some point.

In any case, I find it most important to at most deprecate old parts of the API, so that existing clients have time to adjust. Ideally, they won't even have to, as many will just use it as a simple call wrapper.

When reading through the list of bullet points, one seems to be new in particular: `allow prompts for input to be processed (for credentials)`. I wonder whether this actually has (or should ever) work through git itself. AFAIK, there is the [`GIT_ASKPASS`](https://www.kernel.org/pub/software/scm/git/docs/gitcredentials.html) environment variable just for that purpose.

This project had a mailing list before, and I closed it just because there was nothing happening. By now I do prefer using issues on github for all public communication. If you wish to go ahead with certain refactorings or improvements, you could open an issue for them and discuss the details there. Even though the process is not well defined, we will figure something out as we go, there isn't too many people active on this project after all. I hope that will work for you, as your contributions are greatly appreciated.

**Comment by barry-scott** [comment] 2016-08-03 13:45
On windows git credentials wincred prompts using the terminal stdin/stdout.
That has to be parsed out of the stream as in my case the console window if hidden.

I am working on a prototype of the process control and filtering the work is in:
https://github.com/barry-scott/scm-workbench/blob/master/Source/Git/Experiments/git_cmd.py

Its currently code is python3 only and the windows version is not sane.
Turns out I cannot get away with using half use subprocess Popen. 
I will need to do the full CreateProcess Pattern, which will fix the python2
support I think.

The macos/linux version is showing promise.

python3 git_cmd.py git status

Barry

**Comment by Byron** [comment] 2016-08-04 04:27
Thanks for the heads-up. Looking at the code, I didn't see the usage of `GIT_ASKPASS` anywhere. It's just that I think it's the solution to the 'need to ask for credentials' problem, at least it is what the linked manual suggests.

**Comment by barry-scott** [comment] 2016-08-04 16:44
GIT_ASKPASS is half a solution. I could write a stub that using a named pipe to ask the main GUI for the answers. But that means the GUI must implement the credential storage. I guess I can figure out what git-credentials-wincred.exe does and fake being it.

**Comment by Byron** [comment] 2016-08-05 06:02
I strongly believe `GIT_ASKPASS` works like `[SSH_ASKPASS](http://unix.stackexchange.com/questions/83986/tell-ssh-to-use-a-graphical-prompt-for-key-passphrase)`, which really is nothing but a way to enter the password. It will still be managed by the respective credentials system, so there is nothing to be duplicated here.

**Comment by barry-scott** [comment] 2016-08-05 14:00
Yes you are right the credentials are stored after askpass returns them.
It is unfortunent that you get called twice once for username thne for password.
But nothing that a little state machine cannot solve.

I should have this askpass stuff integrated into scm woekbench soon.

Barry

**Comment by ankostis** [comment] 2016-10-11 17:38
@barry-scott you may take a fresh look at code after some major Windows issues have been resolved in #519 and remaining ones are marked for #525.

**Comment by barry-scott** [comment] 2016-10-11 18:09
@ankostis thanks for the heads up. I will test against trunk and check for regressions.

**Comment by Byron** [comment] 2017-03-08 05:18
I am closing this issue as it had no interaction for more than 3 months. Please feel free to comment in case you need it to be reopened.

**Closed by Byron** 2017-03-08 05:18 UTC
Labels: acknowledged, waiting for feedback

**Comment by hobbitten123** [comment] 2018-06-08 18:37
I am getting this error on apache with mod_wsgi on Redhat 7.2 with python 3.6 ... latest version of gitpython

[Fri Jun 08 13:03:17.584493 2018] [wsgi:error] [pid 21167] [client 10.53.9.7:33473] 2018-06-08 13:03:17,584 - ProcessGit - INFO - push:[]
[Fri Jun 08 13:07:38.056054 2018] [mpm_prefork:notice] [pid 21166] AH00170: caught SIGWINCH, shutting down gracefully
Exception ignored in: <bound method Repo.__del__ of <git.Repo "/opt/xxx/cloud_automation/micro-services/scmprojects/resources/SRV-003106/tst8y9u/.git">>
Traceback (most recent call last):
  File "/usr/venv/lib/python3.6/site-packages/git/repo/base.py", line 200, in __del__
NameError: name 'Exception' is not defined
Exception ignored in: <bound method Popen.__del__ of <subprocess.Popen object at 0x7f0ec97652e8>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/subprocess.py", line 761, in __del__
NameError: name 'ResourceWarning' is not defined
Exception ignored in: <bound method Popen.__del__ of <subprocess.Popen object at 0x7f0ec97659e8>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/subprocess.py", line 761, in __del__
NameError: name 'ResourceWarning' is not defined
Exception ignored in: <bound method Git.AutoInterrupt.__del__ of <git.cmd.Git.AutoInterrupt object at 0x7f0ec9765390>>
Traceback (most recent call last):
  File "/usr/venv/lib/python3.6/site-packages/git/cmd.py", line 372, in __del__
NameError: name 'getattr' is not defined

#-> /usr/sbin/httpd -V
Server version: Apache/2.4.6 (Red Hat Enterprise Linux)
Server built:   Sep 17 2015 09:06:30
Server's Module Magic Number: 20120211:24
Server loaded:  APR 1.4.8, APR-UTIL 1.5.2
Compiled using: APR 1.4.8, APR-UTIL 1.5.2
Architecture:   64-bit
Server MPM:     prefork
  threaded:     no
    forked:     yes (variable process count)
Server compiled with....
 -D APR_HAS_SENDFILE
 -D APR_HAS_MMAP
 -D APR_HAVE_IPV6 (IPv4-mapped addresses enabled)
 -D APR_USE_SYSVSEM_SERIALIZE
 -D APR_USE_PTHREAD_SERIALIZE
 -D SINGLE_LISTEN_UNSERIALIZED_ACCEPT
 -D APR_HAS_OTHER_CHILD
 -D AP_HAVE_RELIABLE_PIPED_LOGS
 -D DYNAMIC_MODULE_LIMIT=256
 -D HTTPD_ROOT="/etc/httpd"
 -D SUEXEC_BIN="/usr/sbin/suexec"
 -D DEFAULT_PIDLOG="/run/httpd/httpd.pid"
 -D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
 -D DEFAULT_ERRORLOG="logs/error_log"
 -D AP_TYPES_CONFIG_FILE="conf/mime.types"
 -D SERVER_CONFIG_FILE="conf/httpd.conf"

**Comment by Byron** [comment] 2018-06-10 18:06
@hobbitten123  Depending on your usecase, you might also be able to *eventually* use https://github.com/Byron/grit-rs , which I just declared the spiritual successor of `GitPython`.

**Comment by sevendays** [comment] 2019-05-17 15:08
Well, it happened to me too. Using python 3.7.3, gitpython 2.1.11, git 2.15.1.windows.1 on Windows10 and running everything from git bash GNU bash, version 4.4.12(1)-release (x86_64-pc-msys)

The app has many checks for existing files and uses sys.exit('error message') if some checks fail.

If everything goes well the app adds a list of files and commits them. Everything used to be smooth when there was only one file added and committed, but when I started having two files added and committed I got this error:

```

Exception ignored in: <function Git.AutoInterrupt.__del__ at 0x000001994C652488>
Traceback (most recent call last):
  File "C:\Users\luca.zamboni\AppData\Local\Programs\Python\Python37\lib\site-packages\git\cmd.py", line 368, in __del__
    if proc.poll() is not None:
  File "C:\Users\luca.zamboni\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 966, in poll
    return self._internal_poll()
  File "C:\Users\luca.zamboni\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1216, in _internal_poll
    if _WaitForSingleObject(self._handle, 0) == _WAIT_OBJECT_0:
OSError: [WinError 6] The handle is invalid

```

## The part of the app causing the error is this one:

```
    ############################################################################
    # Commit the review list file AND the review report file                   #
    ############################################################################

    # get the file relative to repo root
    WPRRlist_path_git = to_native_path_linux(os.path.relpath(os.path.realpath(WPRRlist_path), repo_rootpath)) # reviews list
    WPRR_path_git = to_native_path_linux(os.path.relpath(os.path.realpath(WPRR_newpath), repo_rootpath)) # review report
    repo.index.add([WPRRlist_path_git, WPRR_path_git])
    repo.index.commit(str(repo_path_git)+' review ' + str(result).upper() + 'ED; report: ' + str(WPRR_path_git) + '\n\n' + str(comment))
    print('Report moved to '+WPRR_path_git+' and review committed. You can still go back by discharging this commit.')

    ############################################################################
    # END                                                                      #
    ############################################################################
    exit(0)

```

## The original with only one file added and committed was:

```

    ############################################################################
    # Commit the review list file                                              #
    ############################################################################

    # get the file relative to repo root
    review_repo_path = os.path.relpath(os.path.realpath(csvrevpath), repo_rootpath) # rel path
    repo.index.add([to_native_path_linux(review_repo_path)])
    repo.index.commit(str(repo_path_git)+' review ' + str(result).upper() + 'ED\n\n' + str(comment))
    print('Review committed. You can still go back by discharging this commit.')
    
    ############################################################################
    # END                                                                      #
    ############################################################################
    exit(0)
```


## After reading #718 I added a manual deletion of the repo git object and everything works smooth.

```
    ############################################################################
    # Commit the review list file AND the review report file                   #
    ############################################################################

    # get the file relative to repo root
    WPRRlist_path_git = to_native_path_linux(os.path.relpath(os.path.realpath(WPRRlist_path), repo_rootpath)) # reviews list
    WPRR_path_git = to_native_path_linux(os.path.relpath(os.path.realpath(WPRR_newpath), repo_rootpath)) # review report
    repo.index.add([WPRRlist_path_git, WPRR_path_git])
    repo.index.commit(str(repo_path_git)+' review ' + str(result).upper() + 'ED; report: ' + str(WPRR_path_git) + '\n\n' + str(comment))
    print('Report moved to '+WPRR_path_git+' and review committed. You can still go back by discharging this commit.')

    ############################################################################
    # END                                                                      #
    ############################################################################
    repo.__del__()
    exit(0)
```

So as a workaround manually calling __del__() before calling exit(0) works.
