### ISSUE TITLE
utf-8 branch name issue in SymbolicReference._get_ref_info_helper

### ISSUE THREAD

**Issue by grho** [gitpython-developers/GitPython#954] opened 2019-10-24 12:49 UTC
Hi,
a branch is shown incorrectly when contains utf-8 characters

Branch name: 
```refs/heads/zażółć_gęślą_jaźń```

The issue can be fixed by adding encoding in SymbolicReference._get_ref_info_helper.
Proposed change:
Replace
```python
with open(osp.join(repodir, ref_path), 'rt') as fp:
```
Current result (e.g. shown as active_branch):
```refs/heads/zaÅ¼Ã³Å‚Ä‡_gÄ™Å›lÄ…_jaÅºÅ„```

with
```python
with open(osp.join(repodir, ref_path), 'rt', encoding="utf-8") as fp:
```
Expected result:
```refs/heads/zażółć_gęślą_jaźń```

**Comment by Byron** [comment] 2019-10-28 07:30
Thanks for letting me know! Unfortunately, GitPython is full of encoding issues, and even though assuming UTF-8 isn't technically a perfect fix, it's definitely an improvement over using ASCII implicitly.

I would be happy to receive a PR for that.

**Comment by Harmon758** [comment] 2020-02-18 19:05
Duplicate of #774

**Closed by Harmon758** 2020-02-18 19:05 UTC
Labels: acknowledged, help wanted
