### ISSUE TITLE
Symbolic refs don't parse correctly when a comment appears in the ref file.

### ISSUE THREAD

**Issue by gregbean** [gitpython-developers/GitPython#78] opened 2012-10-18 01:54 UTC
When fetching a ref from a remote server, the ref file can contain a comment, like:

The file FETCH_HEAD:

ecc2505c5d373f8384477cc4d831bbd9323d061c              'refs/my/stuff' of git://my.git/my/repo.git

Because this comment is prefixed with two tabs, it breaks the value.split() call in SymbolicReference._get_ref_info().

**Comment by Byron** [comment] 2015-01-07 12:10
As I am unable to reproduce this issue, I will close it, also referring to the large amount of changes that were introduced in the meanwhile.
If there is still an issue of this kind in the latest release, please file it.

**Closed by Byron** 2015-01-07 12:10 UTC
Labels: acknowledged, feedback
