### ISSUE TITLE
No documentation in API reference

### ISSUE THREAD

**Issue by tsvi** [gitpython-developers/GitPython#1276] opened 2021-06-23 11:08 UTC
It looks like something broke in the infrastructure between 3.1.14 and 3.1.15 as when perusing the latest docs, no reference is available.

I suppose this is due to the renaming of the `master` branch to `main`.

![image](https://user-images.githubusercontent.com/1366384/123086667-63073b80-d42c-11eb-9631-d13019806523.png)

![image](https://user-images.githubusercontent.com/1366384/123086708-6dc1d080-d42c-11eb-8690-ac16349ca00d.png)

**Comment by Byron** [comment] 2021-06-23 12:14
Thanks for posting, it's probably a duplicate of #1235.
There is another thing it is though: A saviour!!!

We were wondering what it could be and you gave the essential hint that let to the solution of the case at hand. The branch renaming is something I would never have suspected, and maybe it wasn't even the issue.

However, perusing the settings in readthedocs revealed that it can handle requirements.txt files as well. After setting the branch and the requirements file name, either one or both of these settings seem to have fixed the issue.

<img width="315" alt="Screenshot 2021-06-23 at 20 07 21" src="https://user-images.githubusercontent.com/63622/123094189-31f42e80-d45f-11eb-9755-1bf113782dd4.png">


<img width="1181" alt="Screenshot 2021-06-23 at 20 11 45" src="https://user-images.githubusercontent.com/63622/123094237-40dae100-d45f-11eb-963c-06b20748c229.png">

Thanks again, I am closing this in anticipation that it works for you too, but feel free to keep posting on the closed issue.

**Closed by Byron** 2021-06-23 12:14 UTC
